language: java
install: true
jdk: oraclejdk9
git:
  depth: false
script: "./travis.sh"
cache:
  directories:
  - "$HOME/.sonar"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  email: false
  on_start: always
