language: java
dist: trusty
install: true
sudo: required
jdk: oraclejdk9
git:
  depth: false
script: "./ci_scripts/travis.sh"
cache:
  directories:
  - '$HOME/.sonar/cache'
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  email: false
  on_start: always
addons:
  sonarcloud:
    organization: "ultimatesoftware"
    token:
      secure: "dz8GJHs67IOOhCGrz3PTywc++dfq3JqnZAZGohXaAWv0A18LxNeYWJpXCgTAZV773yVpg5h23bj5ezH1o5RGyLB+5icVWV6eG+NOJE/sTQesOO+d5fn0mI+EASdMnUxcZ5Se3sH8jSKbDZ6Wt3XyikqZ4yEpyII7NqKIoGcGsCF1jH5lQlaiJ1EZJNwYVXaDhg2vwwR6JcpARuwquIcnwpOp9OUfAyd5d7SqaRzyN5G2mM2btW3dIz+MOtSUVcy68g7KQWEh4fsdfIS9T3PhCbCa/WpZe3nOzlZhresn4sGGXoOX5uUxqs8aQKtrPJAMwTS/In3yNIo3x6louEmvbLcQd6tVNJn5XFgST+npmWcsus3wd7LdYbqnMKCdLf0Nc5+IimElgtp/MatuMkokkq2GtGYVoz33kOGBzKYAlrv08OIPN7CGfQj95ayd223c7mCMHhHk6dxRNjA8YcNa53A+v8I8qFzBql8DsrUJi6Oi9Rtc0qj7aqye/mAu0oTBcyrZVxlVyBICS2nSwSZ5Yn3w2KNa0/ruvQ1DGY3iEmRzsHrBw7LSmQvR70m6X7WYIYfu8v6yhRCxFbwCMlswv1GM4BYYMl0ySSjGq5foU0iLUwLRup0NSlPDi3ovGFCQvstqKRXQS0zv/15CUln/kGmbHW017AwHTVoXvaEP0zI="
stages:
- name: test
- name: build
- name: deploy_snapshot
  if: branch = development
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: build
    script: "./ci_scripts/build.sh"
  - stage: test
    script:
    - "./ci_scripts/test.sh"
    - sonar-scanner -X
  - stage: deploy_snapshot
    script: "./ci_scripts/deploy_snapshot.sh"
  - stage: deploy
    script: "./ci_scripts/deploy.sh"
env:
  global:
  - secure: H+GaDlBztCrYSlo6UQuCGm4lDKwV/0Wi9Hqknt25OIGf4tUgA4WFlK7+z1+Z0dPmoAfRj1ruqNBjNcDzxiEW2gJOfAj9CvvVA/ksqJtEjbaiiUlTPvQBCGlPfJHHMeYpYwh7q9HJaSnPnDao2o8sggKyWjErmZwPY3DpruHj5U861kwy5IAQ4S7kwrUzR0lsv2mnAOyDJKBLb/kku9FpeM+PiFXZxBRo66gBeTS/9m/khXVHKgUrrBAAn7FUAmhcvWb4H9TstF3pt4+uFuh9eTZBSKttvJla7MI4DeqtWAH5N9NqXeiDXpA8K7GBk31TpYd7LUj0Ul1J6W1VtRO1wHyfB1lSLe9xMHUa4/jMdvxjV8v33QFh2g34PFnCBCwlvG+6i890E3ntlk5LtvJHNOWnG7GMoqwBgHEIenYtsWIhhsBxHbM9VSwi98By/L+ap4sbLjP83rq3QAruZo8UFYbLMgSF5czXFtz5N2+D0F7ORLm+H8Ss1UTgsCuB6mUbL9XpFzLToGwZDYJxZbdnT2RyOyxTBd7rD06JOIgkEyExbj9aj99bt0L/AnrwcatOHz2tAv7ww1wxUUZE/kWr9CRQO1z2V85kL5Z7Cz2sHcgrSkVKxQt3IfdqaenBRzpKKnXgrUsdJtXvsFTjaKq2+kyhT5PW+SX8445nHEs3roI=
  - secure: SeWPhfsDkQVuxESNWvOt8VV8GoaOLD9isW1YEXTy03apn/LKIW6EBZ41tt8QBuGBGE+bf6HtGHINgDJETw/JWFXfsk1VO/h4X1QSbUJsJWpu7z3lSPfmFwPjwqjEzIhZKSn54+eyPNArktQpGShU9jyi8AiPhHAKe4SKJbIlkLQfAh6tYwbU0X+1XiKC+tg+hqmgNY4eKbtH5yagfNukVl34XNtdo3txatbXNYKYE1xraHNjnNPAup40K3XUq5u0TMwIWi70mANrJaFCTz/EEIVxfBxGjGBEVrFTDZ1ECNCI4pUDoDTJ0QMWrCqpn/e3q20VdABDOabLEmN2So1Hr/V6bzqJNVE0oTwFho4djaT2AoPo5fkBDzbZnc1JCga0pygcLg2G0fXeG7RoVMhhxn/M7UjVmjiLfMG751k7/2NIFZzfIFq+jfuhuiXJVJwRH7JPjELZa9UqjUrlTmyJaG48l24WsWMJYOnY3geLg//53GHyXmgn0pQV584UHRdrW4lHxf/tDI8kt4yQc/AuVL+us3ZIyZ1wBn29DGVYOkGtKGkzhpv9Tr2SxlwNgeSUDUPvPQpdIm/haz1a/BMN/f+8n/3lxyjqle1UnjIXj2bLXkA94sshbi2JnnVNFVsa7jZrX8ZLXgMlBxpOUGgT6w8Dz4EOOvwQGpzHzpFtDBA=
  - secure: I9W8nr7qQQtBFRbT51rrBMqEmdg1rW8HeVG1HZDvUBuD06w9ziVhWAtFmAJHOULVArZSTfNKoYYPUm0N6VIsjkxsa28PURevKoLqXz5E02FyFBkaIPKU+RKqLSQwBAQdjc2Xrm/MxE2Iohl64iC0l8ixDRJQs2Yw7x4Q9DZsWoCblJ6d8De/qSOLkkurD8CrOKlwSCtFJXLOYRQyC8mb0LcVSIe9gxh301ML87uU/hMd9+Y8UFHIJxHfs/O/YlCXKsoXcYenueLO6UUFnKxBFDfnT7+0SILOmNb7sLiFUrtUNropQSA/4KJKSy20hThpF66fjBAcOlzLVMkj4k5dMwLLstpl8mUMIyPK+xRi0HnRa7sLTP5fsWnUGFHpyO5lCNJd5fnWO9QxrPWz5Q6Kpa2Pwr8pcYYnpt70PC+bo9QU3PUoyiZkLIV/nhGpGFd2TvL8P9xdBfNYU24Jt9bGSOk5ODSIvgKfOZpNuMceXW/RPuQ9OzaJPo5rTXczhdMDYdqiWez74HEMBA1VTyOSeSILGhydHYMsMcBJcgMw/1/fhmTOvaSuunSpZhq1RsHZfHobA2681h72cEm1z77ppB0Wy5sJ6e/NmY3sN0c0k+USeZisdMLlnMWKAWYO+fz6Xwr0iDMSQacYl54o9A4Cr2Lt4C0zR/qYbGeiUkRToLw=
  - secure: EeydwtbuGH8mDX7kZi622OBQbU8CaK8igpbOsIwDRmBFSPe/ASO7gvsgaKU+eZmHKbAfzCuuXw0teevx286SnQoAZbkOgUDGyy7wZBul4X5rLWJZ+sMsyDo1fbTdTqa7SXhG7v0UXhTVMod7vEDJti6ZbM1mKMsT0gxQEnXjYG0vTWekUfrYkgjTuhUGfjT0IGGLTm9xoVWDjHnolEp2QvJAmyEuK+xj/4lAVSjrkdxYnMTJjpzZxFa8uyT4tRH0+vcanudR4ZDUxW7AF+eOnomlTnEvzzTH3FPy/82PNvSB36DrOa/agznV2uAQ69R7+XnbQMyZdtHyFsAQESwby5vRok132PMcjJAhdYiLBTWDYYZKN+IbdRW6dSon+MsIBXvdv61Nlshr/2f7z9RpvhZs2GkQKOPkIqNs6/z7TgGsljVgIL4oBOsNIZKJTgm4vmllZQCmhBsarFRol9iyT5FXfY1z/G4LqW2tyLnvJLuqnZQvPsky6sqtjeZbATB4NjtIG8i9l9ttOx2Rn/1rGXMlnHRtOkBFMRranF01IGT9XZq55zCcXawPZ+HcWa1lde934Q9l1tJ82IIVaIQI1GrV+/kXFPw3YbK/hX2/NdHhL0xsdb8R9blqM23vMRJ0CrE6iJQeBCT8dHvtxT0bb2faNoUPn8mFjETmSu6yDsc=
  - secure: WpgiWOTu+aZ0PgItiUkkDJg1KX3rKDHTKBRoUhFErPr+RhJi9gdGa+okxjjTMwZg3fYcikRQUHjCDC6t4TWvXtULsfrUVbIwJJ5gp8oPwhtsGYwFWIcKAuu1408EF3D3UB9bVss7IKeyLWAREM0/BSbPo6JrMy5yUH2sRtAVS/Dfx2EdWOH2qC8n0XXxEKZDQ7VpdxmaVrS9yHfucgpUu0RadBuyiAIHNSHgvUaPcgYQErtpo07xVzL4MIXqafDzqaUcdlD+vb3E/vYGmsJy0/pZQq1YUNEdiiDkMDGJjybDZQpk56fczDmIZbkJTdRBhKiHyt86fQpNlT4y4JAbaYrC/EOInuCshuHzFJyodnS4ONGxfzFj1HeO4C2THjt0oAgkaluoYinXWoZkQm7dMWbl4MGWjIDFT4pDIpGWIgUAjczMMWtERU5cvBwJR6Y+fyqISuKO10U2B6DT8G3jGXyphw8V7CucfXpzXkXga3wyMaUpkC/W3Mi8K8ndaY7qxJo5l9yfLUaryyt0VH/AAhptQQFnFrDiLlzL+rrWwEOLYyuR6YcWccdH+lvtR7E/ogAk02RAWmUSbbiEoOUAZzKkvExCwpfllHeC99r8Gfu+e1kFBfdPTEnhR7Vy8ZtfOzaRYwPvF6j6Dnl+OS1sfwIkejbTmF3HYoI4h/ySVxg=
